// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/motherboard": {
    params: {};
  };
  "/memory": {
    params: {};
  };
  "/cache": {
    params: {};
  };
  "/cpu": {
    params: {};
  };
  "/gpu": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/motherboard" | "/memory" | "/cache" | "/cpu" | "/gpu" | "/*";
  };
  "routes/motherboard.tsx": {
    id: "routes/motherboard";
    page: "/motherboard";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/memory.tsx": {
    id: "routes/memory";
    page: "/memory";
  };
  "routes/cache.tsx": {
    id: "routes/cache";
    page: "/cache";
  };
  "routes/cpu.tsx": {
    id: "routes/cpu";
    page: "/cpu";
  };
  "routes/gpu.tsx": {
    id: "routes/gpu";
    page: "/gpu";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};