/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/routes/__root";
import { Route as SplashscreenRouteImport } from "./app/routes/splashscreen";
import { Route as MotherboardRouteImport } from "./app/routes/motherboard";
import { Route as MemoryRouteImport } from "./app/routes/memory";
import { Route as GpuRouteImport } from "./app/routes/gpu";
import { Route as CpuRouteImport } from "./app/routes/cpu";
import { Route as CacheRouteImport } from "./app/routes/cache";
import { Route as BatteryRouteImport } from "./app/routes/battery";
import { Route as SplatRouteImport } from "./app/routes/$";
import { Route as IndexRouteImport } from "./app/routes/index";

const SplashscreenRoute = SplashscreenRouteImport.update({
  id: "/splashscreen",
  path: "/splashscreen",
  getParentRoute: () => rootRouteImport,
} as any);
const MotherboardRoute = MotherboardRouteImport.update({
  id: "/motherboard",
  path: "/motherboard",
  getParentRoute: () => rootRouteImport,
} as any);
const MemoryRoute = MemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => rootRouteImport,
} as any);
const GpuRoute = GpuRouteImport.update({
  id: "/gpu",
  path: "/gpu",
  getParentRoute: () => rootRouteImport,
} as any);
const CpuRoute = CpuRouteImport.update({
  id: "/cpu",
  path: "/cpu",
  getParentRoute: () => rootRouteImport,
} as any);
const CacheRoute = CacheRouteImport.update({
  id: "/cache",
  path: "/cache",
  getParentRoute: () => rootRouteImport,
} as any);
const BatteryRoute = BatteryRouteImport.update({
  id: "/battery",
  path: "/battery",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/battery": typeof BatteryRoute;
  "/cache": typeof CacheRoute;
  "/cpu": typeof CpuRoute;
  "/gpu": typeof GpuRoute;
  "/memory": typeof MemoryRoute;
  "/motherboard": typeof MotherboardRoute;
  "/splashscreen": typeof SplashscreenRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/battery": typeof BatteryRoute;
  "/cache": typeof CacheRoute;
  "/cpu": typeof CpuRoute;
  "/gpu": typeof GpuRoute;
  "/memory": typeof MemoryRoute;
  "/motherboard": typeof MotherboardRoute;
  "/splashscreen": typeof SplashscreenRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/battery": typeof BatteryRoute;
  "/cache": typeof CacheRoute;
  "/cpu": typeof CpuRoute;
  "/gpu": typeof GpuRoute;
  "/memory": typeof MemoryRoute;
  "/motherboard": typeof MotherboardRoute;
  "/splashscreen": typeof SplashscreenRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/battery"
    | "/cache"
    | "/cpu"
    | "/gpu"
    | "/memory"
    | "/motherboard"
    | "/splashscreen";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/battery"
    | "/cache"
    | "/cpu"
    | "/gpu"
    | "/memory"
    | "/motherboard"
    | "/splashscreen";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/battery"
    | "/cache"
    | "/cpu"
    | "/gpu"
    | "/memory"
    | "/motherboard"
    | "/splashscreen";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  BatteryRoute: typeof BatteryRoute;
  CacheRoute: typeof CacheRoute;
  CpuRoute: typeof CpuRoute;
  GpuRoute: typeof GpuRoute;
  MemoryRoute: typeof MemoryRoute;
  MotherboardRoute: typeof MotherboardRoute;
  SplashscreenRoute: typeof SplashscreenRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/splashscreen": {
      id: "/splashscreen";
      path: "/splashscreen";
      fullPath: "/splashscreen";
      preLoaderRoute: typeof SplashscreenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/motherboard": {
      id: "/motherboard";
      path: "/motherboard";
      fullPath: "/motherboard";
      preLoaderRoute: typeof MotherboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/memory": {
      id: "/memory";
      path: "/memory";
      fullPath: "/memory";
      preLoaderRoute: typeof MemoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/gpu": {
      id: "/gpu";
      path: "/gpu";
      fullPath: "/gpu";
      preLoaderRoute: typeof GpuRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cpu": {
      id: "/cpu";
      path: "/cpu";
      fullPath: "/cpu";
      preLoaderRoute: typeof CpuRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cache": {
      id: "/cache";
      path: "/cache";
      fullPath: "/cache";
      preLoaderRoute: typeof CacheRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/battery": {
      id: "/battery";
      path: "/battery";
      fullPath: "/battery";
      preLoaderRoute: typeof BatteryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BatteryRoute: BatteryRoute,
  CacheRoute: CacheRoute,
  CpuRoute: CpuRoute,
  GpuRoute: GpuRoute,
  MemoryRoute: MemoryRoute,
  MotherboardRoute: MotherboardRoute,
  SplashscreenRoute: SplashscreenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
